version: 2.1
orbs:
  sixrs-gke: sixriversystems/sixrs-gke@3
jobs:
  prep:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - sixrs-gke/setup-private-npm
      - restore_cache:
          key: |
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - persist_to_workspace:
          root: ./
          paths:
            - .

  lint:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Lint
          command: npm run lint
  tests:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Unit Tests
          command: npm run test:single
      - sixrs-gke/codecov
  publish:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - sixrs-gke/npm-public-publish

workflows:
  version: 2
  test-publish:
    jobs:
      - prep:
          context: 6rs-circle
      - lint:
          requires:
            - prep
          context: 6rs-circle
      - tests:
          requires:
            - prep
          context: 6rs-circle
      - publish:
          requires:
            - prep
            - lint
            - tests
          context: 6rs-public-npm
