version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@7

aliases:
  - &node_image cimg/node:20.15.1
  - &npm_global_cache dependency-cache-v1-{{ checksum ".node-version" }}-{{ checksum "package-lock.json" }}

jobs:
  prep:
    docker:
      - image: *node_image
    steps:
      - checkout
      - sixrs-gke/setup-private-npm
      - restore_cache:
          key: *npm_global_cache
      - run: npm ci
      - save_cache:
          key: *npm_global_cache
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: ./
          paths:
            - ./node_modules

  lint:
    docker:
      - image: *node_image
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run lint

  build:
    docker:
      - image: *node_image
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - .

  tests:
    docker:
      - image: *node_image
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm test
      - sixrs-gke/codecov

  publish:
    docker:
      - image: *node_image
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - sixrs-gke/npm-public-publish

workflows:
  version: 2
  test-publish:
    jobs:
      - prep:
          context: 6rs-circle
      - build:
          requires:
            - prep
          context: 6rs-circle
      - lint:
          requires:
            - prep
          context: 6rs-circle
      - tests:
          requires:
            - build
          context: 6rs-circle
      - publish:
          requires:
            - build
            - lint
            - tests
          context: 6rs-public-npm
